@echo off
echo Stopping existing containers...
docker-compose down

echo Rebuilding the API Docker image...
docker-compose build api

echo Starting services...
docker-compose up -d

echo Waiting for services to initialize...
timeout /t 10

echo Checking API logs...
docker logs filmrecs-api
