@echo off
echo Starting CinematIQ Frontend...
cd /d "D:\Development\CinematIQ\FilmRekommendations.React"
echo Installing dependencies (if needed)...
npm install
echo Starting Vite dev server...
npm run dev
pause