name: Build and Deploy API
on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Debug: show workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          ls -R .

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore NuGet packages
        working-directory: Film-Recommendations/FilmRecomendations.WebApi
        run: dotnet restore

      - name: Build API
        working-directory: Film-Recommendations/FilmRecomendations.WebApi
        run: dotnet build --configuration Release

      - name: Run EF migrations
        working-directory: Film-Recommendations/FilmRecomendations.WebApi
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef database update --no-build
        env:
          ConnectionStrings__FilmConnectionString: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

      - name: Publish API
        working-directory: Film-Recommendations/FilmRecomendations.WebApi
        run: dotnet publish --configuration Release --output publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ai-film-recommendations
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: Film-Recommendations/FilmRecomendations.WebApi/publish
