name: Build and Deploy Frontend
on:
  push:
    branches: [ "master" ]
    # You can add path filters to only run when frontend files change.

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Use a Node version compatible with your project

      - name: Install dependencies
        run: npm ci
        working-directory: FilmRecommendations.Frontend   # Updated directory name

      - name: Build frontend (Vite)
        run: npm run build
        working-directory: FilmRecommendations.Frontend   # Updated directory name

      - name: Deploy to Azure App Service (Frontend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: film-recommendations-frontend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONT }}
          package: FilmRecommendations.Frontend/dist     # Updated directory name
          # slot-name: 'staging'  # optional, if using slots for the frontend app
